version: '3'

      
services:
  jupyter:
    container_name: jupyter-mosquitto
    image: jupyter/scipy-notebook:${JUPYTER_VERSION:-latest}
    volumes:
      - ./notebooks:/home/jovyan/
    ports:
      - 8888:8888

  mosquitto:
    container_name: mosquitto1
    image: eclipse-mosquitto:${MOSQUITTO_VERSION:-latest}
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    expose:
      - 1883
      - 9001
 
  sensorloggerfastapi:
    build: sensor_logger_fast_api_mqtt
    hostname: sensorloggerfastapi
    container_name: sensorloggerfastapi
    ports:
      - 8080:8080
    environment:
      - MQTT_BROKER=mosquitto1
    depends_on: 
      - mosquitto

  cpulogger:
    build: cpu_logger_mqtt
    hostname: cpulogger
    container_name: cpulogger
    environment:
      - MQTT_BROKER=mosquitto1
      - MQTT_TOPIC=cpu/percent
    depends_on: 
      - mosquitto

  mongodb:
    image: mongo:latest
    hostname: mongodb
    container_name: mongodb
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./.data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=cpu


  mongodb_consumer:
    build: mongodb_consumer_mqtt
    hostname: mongodb_consumer
    container_name: mongodb_consumer
    environment:
      - MQTT_BROKER=mosquitto1
      - MQTT_TOPIC=cpu/percent
      - MONGO_DB_CONNECTION_STRING=mongodb://mongoadmin:secret@mongodb:27017/
    depends_on: 
      - mosquitto
      - mongodb